### ISSUE TITLE
Investigate react-table package

### ISSUE THREAD

**Issue by jensren** [reach4help/covidhelphub-frontend#37]
**What:** try to create a simple table using the `react-table` package, with some fake test data. Try to implement sorting, filtering, and searching on the table.

**Out of Scope:**
- We don't need to style the table in this issue. We don't have SemanticUI or styled components merged yet, so styling the table will be another issue.
- The data can be hard-coded. In this issue we are just seeing how easy it is to make a table with `react-table`, so making the table dynamically generated will be another issue.

**Why:** we want to use a package to make it easier to implement table functionality. Before we pick the package, we want to make sure the package is easy to understand and has the functionality we want.

**How:**
- Add `react-table`
- Create a table with some hard-coded fake data
- Try to sort the table by a column
- Try to filter the table
- Investigate what kinds of filters we can apply, and whether we can apply multiple filters
- Investigate whether `react-table` supports searching for specific text in the table

**Comment by Nechir-89** [comment]
### Description
After digging in and applying basic examples of react-table and based on react-table docs, react-table is a set of **hooks** for building tables and data grid. React-table is known as **Headless UI library**  due the fact that it doesn't render or supply any actual UI elements and doesn't have responsibility of styling components and it works this way to keep three features high
- Separation of Concerns: separating UI from handling table behind scenes 
- Maintenance 
- Extensibility 


### Main Features react-table offer
Table features like sorting, filtering, grouping, and etc. can be easily added as each feature has his hook or hooks to get work done, and here are just few of them, to see all the feature please check react-table docs [here](https://react-table.tanstack.com/docs/examples/basic).
- Sorting
- Filtering
- Grouping
- Pagination
- Column expanding
- Row expanding and so many more

### Packages and Files to be added for react-table to get to work
- react-table **Yarn add react-table**
- types **Yarn add @types/react-table**
- Also needs to add types configuration file to fix incomplete type definitions:
 -- create folder **types** inside **src** folder
 -- create **react-table-config.d.ts** file
 -- Copy code code from [here](https://codesandbox.io/s/react-table-incomplete-types-fixed-2r4us?file=/src/types/react-table-config.d.ts) and paste it into your file
 -- You may need to write some ESLint ignoring statements to fix some issues related to ESLint rules.


### Resources
- [React-table documentation](https://react-table.tanstack.com/docs/overview)
- [React-table examples](https://react-table.tanstack.com/docs/examples/basic): all examples can be seen here and for each example there option to run it live on code sandbox for example like [filtering](https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/filtering?file=/src/App.js)
- [YouTube Video](https://youtu.be/WRKEjPq75BY)


### Summery
React-table is table utility and not table component this means it is fully customizable and gives you options to use right tools for your case. React-table may seem complex sometimes as it requires to have knowledge on how the library works and which hook is right for the feature you want to added to the table rather than using component like Material-UI. react-table leaves you the responsibility of UI and styling however there is a good space and easy way to connect other component libraries like bootstrap or Material-UI or even using custom or styled component. 
- [Bootstrap and react-table example](https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/bootstrap-UI-components)
- [Material-UI and react-table example](https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/material-UI-components)

and this report fixes #37
